### ISSUE TITLE
Flux vs Helm or Flux _and_ Helm

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-jupyter#1]
@qcaas-nhs-sjt , thank you for all the work going into this and the other repositories. It will be good for me and the others on the project team that will be working with k8s to learn from you and get a good understanding of how Flux compares with Helm and the advantages of Flux from a CICD perspective. I can see from the code that it will be a shallow learning curve and I am keen that the rest of us get onboard rapidly.

There are a few charts that I am working on (including the OHDSI charts and DataSHIELD with @OllyButters). We can start doing this your way rather than refactoring it at a later stage.

**Comment by vvcb** [comment]
I will have a good read of https://fluxcd.io/flux/use-cases/helm/ but if there are other learning resources, please post them here.

**Comment by qcaas-nhs-sjt** [comment]
My advice would be to use any existing helm charts where possible and apply these using flux. The combination of the two can be really powerful. That said it's not always possible to use pre-existing helm charts, so we'll have to put together our own charts from time to time. I've created a helm chart for the github runners and a flux repository to apply that. I know we could put these together but keeping them separate is better from an open source point of view as we can encourage other people to use and contribute to one library with minimal impact on the other. 

As a result of this you'll note that the helm chart is kept generic so that it can be used in other projects rather than being specific to the SDE and the implementation for the SDE is in flux. I would recommend following this pattern where possible.

**Comment by qcaas-nhs-sjt** [comment]
@vvcb do we need anything more on this ticket or am i good to close?

**Comment by qcaas-nhs-sjt** [comment]
Closed stale ticket
